create table organization_new (
    id bigserial primary key,
    title character varying(255) not null,
    descriptionText character varying(255) not null,
    directorFirstName character varying(255) not null,
    directorSecondName character varying(255) not null,
    directorLastName character varying(255) not null,
    locationCountry character varying(255) not null,
    locationCity character varying(255) not null,
    locationStreet character varying(255) not null,
    locationHomeNumber character varying(255) not null,
    contactsPhone character varying(255) not null,
    contactsVK character varying(255) not null,
    contactsWebSite character varying(255) not null,
    latitude real not null,
    longitude real not null,
    categoryId bigint not null,
    user_login_id bigint not null,
    availableTasksCount int not null default 0,
    availableCouponsCount int not null default 0,
    availableStocksCount int not null default 0,
    photoId bigint not null,
    constraint new_organization_photo_to_photo_fk foreign key (photoId) references photo (id),
    constraint new_organizations_users_fk foreign key (user_login_id) references user_login (id),
    constraint new_organizations_name_uq unique (title),
    constraint new_tasks_categories_fk foreign key (categoryId) references category (id)
);